### ISSUE TITLE
Reduce增加初始值的设定？

### ISSUE THREAD

**Issue by xjqxziii** [xyctruth/stream#24]

**Comment by xyctruth** [comment]
是否可以通过 `Reduce` 接收的函数的第一个参数result 进行判断后初始化？
```go
	stream.NewSlice([]int{1, 2, 3}).Reduce(func(result int, e int) int {
		if result == 0 {
			result = 100
		}
		return result + e
	})
```

**Comment by xjqxziii** [comment]
> 是否可以通过 `Reduce` 接收的函数的第一个参数result 进行判断后初始化？
> 
> ```go
> 	stream.NewSlice([]int{1, 2, 3}).Reduce(func(result int, e int) int {
> 		if result == 0 {
> 			result = 100
> 		}
> 		return result + e
> 	})
> ```

我是想用reduce来产出一个map，需要写成这样
Reduce(func(result map[string]string, element string) map[string]string {
			if result == nil {
				return map[string]string{
					element: element,
				}
			}
			result[element] = element
			return result
		})

然后我试了试，是不是可以增加一个接口，这样子指定默认值
func (stream SliceMappingStream[E, MapE, ReduceE]) Reduce2(result ReduceE, accumulator func(ReduceE, E) ReduceE) ReduceE {
	stream.evaluation()
	if len(stream.source) == 0 {
		return result
	}

	for _, v := range stream.source {
		result = accumulator(result, v)
	}
	return result
}

**Comment by xjqxziii** [comment]
> 是否可以通过 `Reduce` 接收的函数的第一个参数result 进行判断后初始化？
> 
> ```go
> 	stream.NewSlice([]int{1, 2, 3}).Reduce(func(result int, e int) int {
> 		if result == 0 {
> 			result = 100
> 		}
> 		return result + e
> 	})
> ```
```

		Reduce(func(result map[string]string, element string) map[string]string {
			if result == nil {
				return map[string]string{
					element: element,
				}
			}
			result[element] = element
			return result
		})
```
```

func (stream SliceMappingStream[E, MapE, ReduceE]) Reduce2(result ReduceE, accumulator func(ReduceE, E) ReduceE) ReduceE {
	stream.evaluation()
	if len(stream.source) == 0 {
		return result
	}

	for _, v := range stream.source {
		result = accumulator(result, v)
	}
	return result
}
```

**Comment by xyctruth** [comment]
> > 是否可以通过 `Reduce` 接收的函数的第一个参数result 进行判断后初始化？
> > ```go
> > 	stream.NewSlice([]int{1, 2, 3}).Reduce(func(result int, e int) int {
> > 		if result == 0 {
> > 			result = 100
> > 		}
> > 		return result + e
> > 	})
> > ```
> 
> 我想通过reduce生成一个map，然后发现需要这样写
> 
> ```
> 
> 		Reduce(func(result map[string]string, element string) map[string]string {
> 			if result == nil {
> 				return map[string]string{
> 					element: element,
> 				}
> 			}
> 			result[element] = element
> 			return result
> 		})
> ```
> 
> 可以考虑增加一个类似这种的接口吗？这样就可以少初始化一次
> 
> ```
> func (stream SliceMappingStream[E, MapE, ReduceE]) Reduce2(result ReduceE, accumulator func(ReduceE, E) ReduceE) ReduceE {
> 	stream.evaluation()
> 	if len(stream.source) == 0 {
> 		return result
> 	}
> 
> 	for _, v := range stream.source {
> 		result = accumulator(result, v)
> 	}
> 	return result
> }
> ```

ok，稍后会在 `Reduce` 函数直接增加初始值的参数。这样在迭代 Reduce 时可以少做一次判断
